### PR TITLE
Workaround for using v1.1.x

### PR DESCRIPTION
**Pull request by horihiro**
This is workaround for https://github.com/anthonychu/azure-functions-deno-worker/issues/13 (caused by https://github.com/denoland/deno/issues/6409 )

This PR includes:
  - generate wrapper `deno.cmd` as following in `bin\windows` folder during deployment process
    ```
    @echo off
    echo | D:\home\site\wwwroot\bin\windows\deno.exe %*
    ```
  - change `defaultExecutablePath` in `host.json` from `deno.exe` to `deno.cmd` for Windows

Please take a look into this carefully because this is hacky a little.

### CODE REVIEW

**Comment by horihiro** [comment]
By this, it is confirmed that v1.1.1 works on Windows Function App (Consumption, App Service Plan and Elastic Premium).
image

A process tree in Function App is following after depoloyment.

image

**Comment by anthonychu** [comment]
Let's wait to see if https://github.com/denoland/deno/pull/6528 gets merged.

**Comment by horihiro** [comment]
I agree with you!
Thanks!

**Comment by horihiro** [comment]
Fixed version will be released soon
https://github.com/denoland/deno/issues/6409#issuecomment-656931299

**Comment by horihiro** [comment]
Please close this if `deno` v1.1.x will not be supported.
I confirmed `deno` v1.2.0 deployed by `denofunc` v0.4.0 works fine on a Function App.

**Pull request closed without merging**
